In [1]:
## intially Lets import numpy

import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr = np.array((1,2,3,4,5,6))
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Creat an array with specified data type

arr = np.array([[1,2,3],[4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
print('Data Type:'+ str(arr.dtype))

Data Type:int16


In [10]:
#Create an array with specified data type
#np.arange() method can be used to replace np.array(range()) method

In [11]:
#np. arange(start, stop, step)
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr = np.linspace(0,5,8)
print(arr)

[0.         0.71428571 1.42857143 2.14285714 2.85714286 3.57142857
 4.28571429 5.        ]


In [13]:
arr, step_size = np.linspace(0,5,8, endpoint=False, retstep=True)
print(arr)

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]


In [14]:
print(str(step_size))

0.625


In [17]:
arr = np.random.rand(2,2)
print(arr)

[[0.35599338 0.15986251]
 [0.13349263 0.00236847]]


In [18]:
arr = np.random.rand(3,3)

In [19]:
arr

array([[0.833612  , 0.54986628, 0.38636461],
       [0.09900877, 0.2731573 , 0.7737853 ],
       [0.50747654, 0.05365677, 0.71275497]])

In [20]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
arr = np.array([[1,2],[3,4],[5,6]], dtype=np.complex64)
print(arr)
print('********')
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type' + str(zeros.dtype))

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]
********
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Typecomplex64


In [25]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [27]:
arr = [[1,2,3],[4,5,6]]
ones = np.ones_like(arr)
print(ones)

[[1 1 1]
 [1 1 1]]


In [28]:
empty = np.empty((5,5))
print(empty)

[[1.11261027e-306 1.78021663e-306 1.11261570e-306 8.90060780e-307
  7.56525113e-307]
 [4.00544531e-307 1.11261095e-306 3.22651328e-307 1.37962320e-306
  1.78019761e-306]
 [1.33511562e-306 1.69121775e-306 7.56603881e-307 3.22641142e-307
  6.23060405e-307]
 [1.02360935e-306 1.69120416e-306 1.78022342e-306 4.45061456e-308
  6.23040033e-307]
 [1.11260348e-306 1.37962049e-306 2.22521238e-306 1.24611470e-306
  2.10077583e-312]]


In [32]:
empty = np.empty((2,2))
print(empty)

[[0.35599338 0.15986251]
 [0.13349263 0.00236847]]


In [33]:
arr = np.array([[1,2,3],[4,5,6]])
empty = np.empty_like(arr)
print(empty)

[[1 2 3]
 [4 5 6]]


In [34]:
arr = np.array([[1,2,3],[4,5,6]], dtype=np.int64)
print(arr)

print('########')

empty = np.empty_like(arr)
print(empty)

[[1 2 3]
 [4 5 6]]
########
[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]


In [38]:
empty = np.empty((2,3))
empty

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
full = np.full((4,4),5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [41]:
arr = np.array([[1,2],[3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type:'+ str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type:float64


In [42]:
#no axis spsecified 
arr = [[0,1,2],[3,4,5]]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [44]:
arr = [[0,1,2],[4,5,6]]
print(np.repeat(arr,2))

[0 0 1 1 2 2 4 4 5 5 6 6]


In [47]:
#An example of repeating along x-axis

arr = [[0,1,2],[3,4,5]]
print(np.repeat(arr, 3, axis=0))

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [48]:
# An example of reppeating  along y-axis

arr = [[0,1,2],[3,4,5]]
print(np.repeat(arr, 3, axis=1))

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [50]:
# repeat thwe whole array by a specified nummber of times

arr = [0,1,2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [52]:
#Repeat along specified axis
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [53]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [54]:
#An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [55]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [56]:
arr = np.random.rand(5,5)
print(arr)
# Extract values on diagonal
print('Values on diagonal:' +str(np.diag(arr)))

[[0.62732933 0.98212737 0.90692303 0.51942504 0.66670729]
 [0.2567819  0.39305298 0.29709873 0.3291793  0.67019069]
 [0.29142687 0.8951414  0.03282395 0.70958141 0.66173958]
 [0.65232018 0.92801558 0.63581442 0.04992668 0.0811111 ]
 [0.04025256 0.4453987  0.50215379 0.82953493 0.50330587]]
Values on diagonal:[0.62732933 0.39305298 0.03282395 0.04992668 0.50330587]


In [57]:
arr = np.random.rand(10,3)
print(arr)
# Extract values on diagonal
print('Values on diagonal:' +str(np.diag(arr)))

[[0.42234137 0.68231474 0.5183921 ]
 [0.98913393 0.23732263 0.20792076]
 [0.29596753 0.87533289 0.60720685]
 [0.70293304 0.63551619 0.57376552]
 [0.77600796 0.82733771 0.0044098 ]
 [0.58219675 0.4761319  0.24502553]
 [0.29756581 0.26570654 0.5483937 ]
 [0.87877612 0.42293592 0.21321079]
 [0.18089634 0.35719733 0.14286487]
 [0.3220963  0.99369305 0.54669014]]
Values on diagonal:[0.42234137 0.23732263 0.60720685]


In [58]:
#create a matrix given values on the diagonal
#All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [62]:
print(np.random.seed(123))

None


In [64]:
rs = np.random.RandomState(321)
print(rs.rand(10))

[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472 0.52667564
 0.90755375 0.8840703  0.08926896 0.5173446 ]


In [65]:
#generate a  random scalar
print(np.random.rand())

0.6964691855978616


In [66]:
#generate a 1-D array
print(np.random.rand(3))

[0.28613933 0.22685145 0.55131477]


In [69]:
#generate a 2-D array
print(np.random.rand(3,3))

[[0.53182759 0.63440096 0.84943179]
 [0.72445532 0.61102351 0.72244338]
 [0.32295891 0.36178866 0.22826323]]


In [70]:
#generate a sample from the standard normal distribution
print(np.random.randn(3,3))

[[ 0.9071052  -1.4286807  -0.14006872]
 [-0.8617549  -0.25561937 -2.79858911]
 [-1.7715331  -0.69987723  0.92746243]]


In [71]:
#generate an array of random integers in agiven interval[low, high]
# np.random.randint(low, high, size, dtype)
print(np.random.randint(1,10,3,'i8'))

[5 7 4]


In [72]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.56843069 0.30254945 0.49730879 0.68326291 0.91669867 0.10892895
 0.49549179 0.23283593 0.43686066 0.75154299]
[0.48089213 0.79772841 0.28270293 0.43341824 0.00975735 0.34079598
 0.68927201 0.86936929 0.26780382 0.45674792]
[0.26828131 0.8370528  0.27051466 0.53006201 0.17537266 0.31496645
 0.8911091  0.18033628 0.4943162  0.2122981 ]
[0.52087687 0.16009994 0.9190568  0.99428992 0.47704756 0.30988351
 0.50720432 0.2807932  0.76383669 0.1085423 ]


In [73]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3),10, replace=True, p=[0.1, 0.8, 0.1]))

[1 2 1 1 1 1 1 1 1 1]


In [83]:
print(np.random.choice(5,10))

[4 1 2 1 4 1 3 4 2 2]


In [84]:
print(np.random.choice([1,2,3],10))

[1 1 3 2 2 2 2 2 3 3]


In [76]:
#shuffle an array in place
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [77]:
np.random.shuffle(arr)
print(arr)

[4 8 3 5 2 0 7 9 1 6]


In [78]:
arr = np.array(range(10))
print('The intial array:',arr)
print('A permutation of the array:', np.random.permutation(arr))

The intial array: [0 1 2 3 4 5 6 7 8 9]
A permutation of the array: [2 0 6 8 9 3 4 5 7 1]


In [88]:
print(np.random.randint(1,10,5))

[8 7 4 2 8]


In [94]:
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
arr[3:]=100

In [91]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [92]:
arr[arr<5]

array([0, 1, 2])

In [93]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [95]:
val = 2
arr[arr<3]

array([0, 1, 2])

In [96]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [97]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)
zeros = np.zeros_like(arr)
print(zeros)

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


In [98]:
arr

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]], dtype=complex64)

In [104]:
empty = np.empty((3,3))
print(empty)

[[ 0.9071052  -1.4286807  -0.14006872]
 [-0.8617549  -0.25561937 -2.79858911]
 [-1.7715331  -0.69987723  0.92746243]]


In [108]:
full = np.full((4,4),0)
print(full)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [109]:
arr = [[0,1,2],[3,4,5]]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [110]:
arr =[[0,1,2],[3,4,5]]

In [112]:
print(np.repeat(arr,3,axis=1))

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [114]:
arr = [0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [117]:
print(np.tile(arr, (3,3)))

[[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]


In [119]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [120]:
identity_matrix = np.eye(5,k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [121]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [122]:
arr = np.random.rand(10,3)
print(arr)

[[0.58404612 0.47746048 0.17151502]
 [0.05662    0.15703523 0.3386175 ]
 [0.44064297 0.68384312 0.20587172]
 [0.6164337  0.92447161 0.07962825]
 [0.48539683 0.69856363 0.08156848]
 [0.86910236 0.43310568 0.49433006]
 [0.49574047 0.37072208 0.92212866]
 [0.84127822 0.65552592 0.46268505]
 [0.56501131 0.42391551 0.28821195]
 [0.26398072 0.69073823 0.83283653]]


In [123]:
print(str(np.diag(arr)))

[0.58404612 0.15703523 0.20587172]


In [124]:
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [126]:
import numpy as np
import pandas as pd

In [130]:
df = pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',sep='\t')

In [131]:
df.head()

item_code                                          item_name  display_level  \
0       AA0                               All items - old base              0   
1      AA0R  Purchasing power of the consumer dollar - old ...              0   
2       SA0                                          All items              0   
3      SA0E                                             Energy              1   
4     SA0L1                                All items less food              1   

  selectable  sort_sequence  
0          T              2  
1          T            399  
2          T              1  
3          T            374  
4          T            358

In [132]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(Data)

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [134]:
pd.(Data)

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [136]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

In [139]:
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [140]:
# convert Json  to csv

In [141]:
df.to_csv('wine.csv')

In [145]:
df.to_json(orient="index")

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3

In [147]:
df.to_json(orient='records')

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"

In [151]:
url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs = pd.read_html(url_mcc, match='Country', header=0)


In [155]:
dfs[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
5                    213                                    Andorra       AD   
6                    631                                     Angola       AO   
7                    365                  Anguilla (United Kingdom)       AI   
8                    344                        Antigua and Barbuda       AG   
9                    722                                  Argentina       AR   
10                   283                                    Armenia       AM   
11                   363                                      Aruba       AW   
12                   505                                  Australia       AU   
13                   232                                    Austria       AT   
14                   400                                 Azerbaijan       AZ   
15                   364                                  B Bahamas       BS   
16                   426                                    Bahrain       BH   
17                   470                                 Bangladesh       BD   
18                   342                                   Barbados       BB   
19                   257                                    Belarus       BY   
20                   206                                    Belgium       BE   
21                   702                                     Belize       BZ   
22                   616                                      Benin       BJ   
23                   350                                    Bermuda       BM   
24                   402                                     Bhutan       BT   
25                   736                                    Bolivia       BO   
26                   362           Bonaire, Sint Eustatius and Saba       BQ   
27                   218                     Bosnia and Herzegovina       BA   
28                   652                                   Botswana       BW   
29                   724                                     Brazil       BR   
..                   ...                                        ...      ...   
222                  374                        Trinidad and Tobago       TT   
223                  605                                    Tunisia       TN   
224                  286                                     Turkey       TR   
225                  438                               Turkmenistan       TM   
226                  376                   Turks and Caicos Islands       TC   
227                  553                                     Tuvalu       TV   
228                  641                                   U Uganda       UG   
229                  255                                    Ukraine       UA   
230                  424                       United Arab Emirates       AE   
231                  430           United Arab Emirates (Abu Dhabi)       AE   
232                  431               United Arab Emirates (Dubai)       AE   
233                  234                             United Kingdom       GB   
234                  235                             United Kingdom       GB   
235                  310                   United States of America       US   
236                  311                   United States of America       US   
237                  312                   United States of America       US   
238                  313                   United States of America       US   
239                  314                   United States of America       US   
240  

In [157]:
lst_data = [[1,2,3],[3,4,np.nan],[5,6,np.nan],[np.nan,np.nan,np.nan]]

In [158]:
df = pd.DataFrame(lst_data)

In [159]:
df.head()

0    1    2
0  1.0  2.0  3.0
1  3.0  4.0  NaN
2  5.0  6.0  NaN
3  NaN  NaN  NaN

In [161]:
df = pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'],
                 columns = ['one','two','three'])

In [162]:
df.head()

one       two     three
a -0.173636 -0.869044  2.398402
c -1.001390  1.602473  1.498786
e  0.525211  0.831080  0.022368
f -0.069009 -1.933373 -0.592466
h -0.944294  1.301994 -1.130536

In [163]:
df2 = df.reindex(['a','b','c','d','e','f','g','h'])

In [164]:
df2

one       two     three
a -0.173636 -0.869044  2.398402
b       NaN       NaN       NaN
c -1.001390  1.602473  1.498786
d       NaN       NaN       NaN
e  0.525211  0.831080  0.022368
f -0.069009 -1.933373 -0.592466
g       NaN       NaN       NaN
h -0.944294  1.301994 -1.130536