In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [21]:
## multinested array
my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [9,7,6,8,9]

In [22]:
arr = np.array([my_list1,my_list2,my_list3])

In [23]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.shape

(3, 5)

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [14]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [15]:
# check the shape of the array

arr.shape

(3, 5)

In [ ]:
#Indexing

In [17]:
#Accessing the array elements

arr = np.array([1,2,3,4,5,6,7,8,9])

In [18]:
arr[3]

4

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [28]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [29]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [30]:
arr = np.arange(0,10)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr = np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [36]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [37]:
#Copy function and broadcasting
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[3:] =100

In [39]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [40]:
arr1 = arr

In [41]:
arr1[3:]=500

In [42]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [43]:
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [44]:
arr1=arr.copy()

In [45]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [46]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [47]:
arr1

array([   1,    2,    3, 1000, 1000, 1000, 1000, 1000, 1000])

In [48]:
### Some Conditions very useful in Exploratory Data Ananlysis

val = 2

arr<2  #It gives true or false values

array([ True, False, False, False, False, False, False, False, False])

In [51]:
arr[arr<300] #this condition gives the values

array([1, 2, 3])

In [49]:
arr*2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [50]:
arr//2

array([  0,   1,   1, 250, 250, 250, 250, 250, 250], dtype=int32)

In [52]:
#Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
arr1 = np.arange(0,10).reshape(2,5)

In [54]:
arr2 = np.arange(0,10).reshape(2,5)

In [55]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [56]:
np.ones(4) #by default dtype is float we can also change dtype

array([1., 1., 1., 1.])

In [57]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [61]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [62]:
### Random Distribution 
np.random.rand(3,3)

array([[0.66214736, 0.29644423, 0.56946065],
       [0.11916703, 0.88068012, 0.79321688],
       [0.45911125, 0.76083768, 0.10503555]])

In [63]:
arr_ex = np.random.randn(4,4)

In [64]:
arr_ex

array([[ 0.07044454,  2.06716788,  0.38101381,  1.56581254],
       [ 0.38673923,  0.03214451,  0.19006238,  0.53821439],
       [ 0.48561789, -0.27894001,  0.20183168,  0.99602787],
       [ 0.3588434 , -0.01179733,  0.08981468,  0.21094639]])

In [65]:
np.random.randint(0,100,8)

array([64, 73, 84, 66,  1, 13, 14, 78])

In [66]:
np.random.randint(0,100,8).reshape(2,4)

array([[94, 73, 73, 70],
       [91, 22, 18, 58]])

In [68]:
np.random.random_sample((1,5))

array([[0.44480459, 0.12644277, 0.7473765 , 0.51290511, 0.33069727]])